project-YoNoRush-main/WorkoutCompanion/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('input/', views.user_input, name='user_input'),
    path('sign-up/', views.sign_up, name='signup'),
    path('log-in/', views.log_in, name='login'),
    path('view-workout-info/', views.view_workout_info, name='view_workout_info'),
    path('logout/', views.logginOut, name='logout'),
]

project-YoNoRush-main/termproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WorkoutCompanion.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project-YoNoRush-main/WorkoutCompanion/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.db import models

class WorkoutCompanion(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
    ]

    GOAL_CHOICES = [
        ('Lose Weight', 'Lose Weight'),
        ('Gain Weight', 'Gain Weight'),
        ('Gain Muscle', 'Gain Muscle'),
    ]

    user_first_name = models.CharField(max_length=30)
    user_last_name = models.CharField(max_length=30)
    user_age = models.IntegerField()
    user_gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    user_weight = models.FloatField()
    user_height = models.FloatField()
    user_workout_choice = models.CharField(max_length=12, choices=GOAL_CHOICES)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)

    def __str__(self):
        if self.user:
            return f"Workout Companion for {self.user.username}"
        return "Workout Companion with no user"

project-YoNoRush-main/WorkoutCompanion/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import WorkoutCompanion
from django.db import models


class UserInputForm(forms.ModelForm):
    class Meta:
        model = WorkoutCompanion
        fields = ['user_first_name', 'user_last_name', 'user_age', 'user_gender', 'user_weight', 'user_height', 'user_workout_choice', 'profile_picture']
        widgets = {
            'user_gender': forms.RadioSelect,
            'user_workout_choice': forms.RadioSelect,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_gender'].choices = list(filter(lambda choice: choice[0], self.fields['user_gender'].choices))
        self.fields['user_workout_choice'].choices = list(filter(lambda choice: choice[0], self.fields['user_workout_choice'].choices))

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already taken.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already in use.")
        return email

project-YoNoRush-main/WorkoutCompanion/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from .models import WorkoutCompanion
from .forms import UserInputForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm



def index(request):
    WorkoutCompanions = WorkoutCompanion.objects.all()
    return render(request, 'index.html', {'WorkoutCompanions': WorkoutCompanions})

def user_input(request):
    try:
        workout_info = request.user.workoutcompanion
    except WorkoutCompanion.DoesNotExist:
        workout_info = None

    if request.method == 'POST':
        form = UserInputForm(request.POST, request.FILES, instance=workout_info)
        if form.is_valid():
            companion = form.save(commit=False)
            companion.user = request.user
            companion.save()
            return redirect('login')
    else:
        form = UserInputForm(instance=workout_info)

    return render(request, 'user_input.html', {'form': form})

def sign_up(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('user_input')
    else:
        form = CustomUserCreationForm()
    return render(request, 'signup.html', {'form': form})

def log_in(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('view_workout_info')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


@login_required
def view_workout_info(request):
    try:
        workout_info = request.user.workoutcompanion
    except WorkoutCompanion.DoesNotExist:
        workout_info = None
    user = request.user
    caloric_intake = round(caloric_calculator(user))
    return render(request, 'view_workout_info.html', {'workout_info': workout_info, 'caloric_intake': caloric_intake })

@login_required
def logginOut(request):
    logout(request)
    return redirect('index')

def caloric_calculator(user):

    if user.workoutcompanion.user_gender == 'Male':
        Total_Daily_Energy_Expend = (10 * user.workoutcompanion.user_weight + 6.25 * user.workoutcompanion.user_height - 5
               * user.workoutcompanion.user_age + 5) * 1.425
        if user.workoutcompanion.user_workout_choice == 'Lose Weight':
            return Total_Daily_Energy_Expend - 500
        else:
            return Total_Daily_Energy_Expend + 500


    elif user.workoutcompanion.user_gender == 'Female':
        Total_Daily_Energy_Expend = (10 * user.workoutcompanion.user_weight + 6.25 * user.workoutcompanion.user_height - 5
               * user.workoutcompanion.user_age - 161) * 1.425
        if user.workoutcompanion.user_workout_choice == 'Lose Weight':
            return Total_Daily_Energy_Expend - 500
        else:
            return Total_Daily_Energy_Expend + 500

project-YoNoRush-main/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Workout Companion</title>
</head>
<body>
 <h1>Welcome to Workout Companion</h1>
    <p>Please <a href="{% url 'signup' %}">sign up</a> or <a href="{% url 'login' %}">log in</a> to continue.</p>
</body>
</html>

project-YoNoRush-main/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Log In</title>
</head>
<body>
    <h1>Log In</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <p>Don't have an account? <a href="{% url 'signup' %}">Sign Up</a></p>
</body>
</html>

project-YoNoRush-main/templates/logout.html
<p>Welcome! <a href="{% url 'logout' %}">Log Out</a></p>

project-YoNoRush-main/templates/signup.html
<!DOCTYPE html>
<html>
<head>
    <title>Sign Up</title>
</head>
<body>
    <h1>Sign Up</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% for field in form %}
        {% if field.errors %}
            <div style="color: red;">
                {{ field.label }}: {{ field.errors|striptags }}
            </div>
        {% endif %}
    {% endfor %}
    <button type="submit">Sign Up</button>
    </form>
    <p>Already have an account? <a href="{% url 'login' %}">Log In</a></p>
</body>
</html>

project-YoNoRush-main/templates/user_input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>User Input</title>
</head>
<body>
    <h1>Enter Your Information</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>
            <label for="id_user_first_name">First Name:</label>
            {{ form.user_first_name }}
        </p>
        <p>
            <label for="id_user_last_name">Last Name:</label>
            {{ form.user_last_name }}
        </p>
        
        <p>
            <label for="id_profile_picture">Profile Picture:</label>
            {{ form.profile_picture }}
            <!-- <button type="submit">Save</button> -->
        </p>
        
        <p>
            <label for="id_user_age">Age:</label>
            {{ form.user_age }}
        </p>
        <p>
            <label>Gender:</label>
            {{ form.user_gender }}
        </p>
        <p>
            <label for="id_user_weight">Weight (kg):</label>
            {{ form.user_weight }}
        </p>
        <p>
            <label for="id_user_height">Height (cm):</label>
            {{ form.user_height }}
        </p>
        <p>
            <label>Workout Goal:</label>
            {{ form.user_workout_choice }}
        </p>
        <button type="submit">Submit</button>
    </form>
</body>
</html>

project-YoNoRush-main/templates/view_workout_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Workout Information</title>
    <link rel="stylesheet" href="../styles/view_workout_info_styles.css">

</head>
<body>
    {% if workout_info %}
        <h1>Workout Companion Info</h1>
        <p>First Name: {{ workout_info.user_first_name }}</p>
        <p>Last Name: {{ workout_info.user_last_name }}</p>

        {% if workout_info.profile_picture %}
            <img src="{{ workout_info.profile_picture.url }}" alt="Profile Picture" width="150" height="150">
        {% else %}
            <p>No profile picture uploaded.</p>
        {% endif %}

        <p>Age: {{ workout_info.user_age }}</p>
        <p>Gender: {{ workout_info.user_gender }}</p>
        <p>Weight: {{ workout_info.user_weight }} kg</p>
        <p>Height: {{ workout_info.user_height }} cm</p>
        <p>Workout Choice: {{ workout_info.user_workout_choice }}</p>

        <a href="{% url 'user_input' %}"><button>Edit</button></a>
        <a href="{% url 'logout' %}"><button>Logout</button></a>
    {% else %}
        <p>No workout companion information found.</p>
            <a href="{% url 'user_input' %}"><button>Create</button></a>
    {% endif %}


    {% if workout_info.user_workout_choice == 'Lose Weight' %}

        <p>Based off the information you put in, you need to
            consume about <b> {{ caloric_intake }}</b> calories a day to lose weight.</p>

        <h2>Workouts to lose weight:</h2>

        <h3>Tuesday:</h3>
        <p>Running: 20 minutes at a moderate pace</p>
        <p>Jump Squats: 3 sets x 15 reps</p>
        <p>Burpees: 3 sets x 12 reps</p>
        <p>Mountain Climbers: 3 sets x 30 seconds</p>
        <p>High Knees: 3 sets x 30 seconds</p>

        <h3>Thursday:</h3>
        <p>Interval Running: 5 rounds of 30 seconds sprint + 1-minute walk</p>
        <p>Push-ups: 3 sets x 15 reps</p>
        <p>Jumping Lunges: 3 sets x 10 reps (each leg)</p>
        <p>Tuck Jumps: 3 sets x 12 reps</p>
        <p>Flutter Kicks: 3 sets x 20 reps</p>

        <h3>Saturday:</h3>
        <p>Long-Distance Running: 30 minutes at an easy pace</p>
        <p>Burpee-to-Push-up: 3 sets x 10 reps</p>
        <p>Broad Jumps: 3 sets x 10 reps</p>
        <p>Bicycle Crunches: 3 sets x 20 reps</p>
        <p>Side Plank: 3 sets x 30 seconds (each side)</p>

    {% endif %}


    {% if workout_info.user_workout_choice == 'Gain Weight' %}

        <p>Based off the information you put in, you need to
            consume about <b>{{ caloric_intake }}</b> calories a day to gain weight.</p>

        <h2>Workouts to gain weight:</h2>
        <h3>Tuesday:</h3>
        <p>Bodyweight Squats: 4 sets x 12 reps</p>
        <p>Push-ups: 4 sets x 15 reps</p>
        <p>Pull-ups: 4 sets x 10 reps</p>
        <p>Dips: 4 sets x 10 reps</p>
        <p>Plank to Shoulder Tap: 3 sets x 20 taps</p>

        <h3>Thursday:</h3>
        <p>Bulgarian Split Squats: 3 sets x 12 reps (each leg)</p>
        <p>Archer Push-ups: 3 sets x 8 reps (each side)</p>
        <p>Chin-ups: 4 sets x 8 reps</p>
        <p>Superman Hold: 3 sets x 30 seconds</p>
        <p>Side Plank: 3 sets x 30 seconds (each side)</p>

        <h3>Saturday:</h3>
        <p>Jump Squats: 3 sets x 10 reps</p>
        <p>Diamond Push-ups: 3 sets x 12 reps</p>
        <p>Wide-Grip Pull-ups: 3 sets x 10 reps</p>
        <p>L-sit: 3 sets x 20 seconds</p>
        <p>Leg Raises: 3 sets x 15 reps</p>


    {% endif %}


    {% if workout_info.user_workout_choice == 'Gain Muscle' %}

        <p>To build muscle optimally, you should consume
            about <b>{{ caloric_intake }} calories</b> a day.</p>

        <h2>Workouts to gain muscle:</h2>
                <h3>Tuesday:</h3>
        <p>Bulgarian Split Squats: 4 sets x 10 reps (each leg)</p>
        <p>Archer Push-ups: 4 sets x 8 reps (each side)</p>
        <p>Wide-Grip Pull-ups: 4 sets x 8 reps</p>
        <p>Dips: 4 sets x 10 reps</p>
        <p>Hollow Body Hold: 3 sets x 30 seconds</p>

        <h3>Thursday:</h3>
        <p>Pistol Squats: 3 sets x 6 reps (each leg)</p>
        <p>Handstand Push-ups (or Pike Push-ups): 3 sets x 8 reps</p>
        <p>Chin-ups: 4 sets x 10 reps</p>
        <p>Superman Hold: 3 sets x 30 seconds</p>
        <p>Side Plank Hip Raises: 3 sets x 12 reps (each side)</p>

        <h3>Saturday:</h3>
        <p>Jump Squats: 3 sets x 12 reps</p>
        <p>Diamond Push-ups: 3 sets x 10 reps</p>
        <p>Pull-ups (Weighted if possible): 4 sets x 8 reps</p>
        <p>L-sit to Tuck Hold: 3 sets x 20 seconds</p>
        <p>Hanging Leg Raises: 3 sets x 15 reps</p>
    {% endif %}


</body>
</html>